# NOTE: This file was generated via generate.sh. Don't edit it directly

name: GitHub CI

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  verify-templating:
    name: Verify templating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate
        run: make all
      - name: Check Git status
        run: |
          test -z "$(git status --short)"

  docker:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs:
      - verify-templating
    strategy:
      matrix:
        target:
          [
            "7.4.30-bullseye",
            "7.4.30-buster",
            "7.4.30-alpine3.16",
            "7.4.30-alpine3.15",
            "8.0.22-bullseye",
            "8.0.22-buster",
            "8.0.22-alpine3.16",
            "8.0.22-alpine3.15",
            "8.1.9-bullseye",
            "8.1.9-buster",
            "8.1.9-alpine3.16",
            "8.1.9-alpine3.15",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Hub build and push
        uses: docker/bake-action@master
        with:
          targets: ${{ matrix.target }}
          push: ${{ github.event_name == 'push' }}
      - name: GHCR build and push
        uses: docker/bake-action@master
        with:
          files: docker-bake.hcl,docker-bake-ghcr.hcl
          targets: ${{ matrix.target }}
          push: ${{ github.event_name == 'push' }}
